---
title: "Data_formatting"
author: "Christopher Rounds"
date: "3/15/2022"
output: html_document
---

```{r setup, include=FALSE, message =FALSE}
library(tidyverse)
library(ggplot2)
library(readxl) 
library(lubridate)
library(gt)
library(randomForest)
library(mcmcplots)
options(scipen = 999)

read_excel_allsheets <- function(filename, tibble = FALSE) {
    sheets <- readxl::excel_sheets(filename)
    x <- lapply(sheets, function(X) readxl::read_excel(filename, sheet = X))
    if (!tibble) x <- lapply(x, as.data.frame)
    names(x) <- sheets
    x
}

detect.likeli = function(p, a = 0.95){ 
#given a prob of detection (p) and confidence (a), calculates samples required
  log(1 - a)/log(1 - p)
}

logit = function(x) {
  exp(x)/(1+exp(x))
}
site_covariate_data <- read_excel_allsheets("./data/field_data/Activity_1_eDNA_Field_Data_2021.xlsx")

profiles <- site_covariate_data$Temp_DO_Profiles #contains profiles
sample_data <- site_covariate_data$A1_Samples #contains sample covariate data
physical <- site_covariate_data$Lakes #contains lake physical data (site level)

qpcr_data <- read.csv("./data/04-Jan-2023_qPCR_activity_one_results.csv") #qPCR data

```


```{r profile.data.cleaning}
covariate_data <- profiles %>%
  dplyr::select("Date", "Lake", "Visit #", "UID", "Depth_m", "Temp_C", 
         "DO_mgL", "cond", "pH", "Clarity_m") %>%
  mutate(Date = as.Date(Date),
         Lake = as.factor(Lake)) %>%
  rename("visit_number" = "Visit #") %>%
  group_by(UID) %>%
  mutate(max_depth = max(Depth_m))

covariate_data %>%
  group_by(Lake) %>%
  count(visit_number) %>%
  summarise(n = n())
# every lake should have 5 observations corresponding to a sampling event
```



```{r lake_visit}
# probably the worst code I have ever wrote so apologies, for the life of me I couldn't figure out a tidy way to do this. What I am doing is looking at the temperature profile from each lake visit to see if there is at least a 2 deg C difference in temperature. If there is a 2 deg C difference in temp, stratified is classified as TRUE and the depth where the difference occurs is recorded.

stratify_zm <- data.frame("UID" = character(1), "stratified" = character(1), "strat_zm" = numeric(1))
sites <- unique(covariate_data$UID)
max_depth <- 0; i <- 1; temp_site <- covariate_data$UID[1]; surface_temp <- covariate_data$Temp_C[1]
stratified = FALSE
for (row in 1:nrow(covariate_data)) {
  if (temp_site != covariate_data$UID[row]) {
    stratify_zm[i,1] <- temp_site
    stratify_zm[i,2] <- stratified
    stratify_zm[i,3] <- max_depth
    i <- i + 1
    surface_temp <- covariate_data$Temp_C[row]
    temp_site <- covariate_data$UID[row]
    stratified = FALSE
  } 
  else {
    if (stratified == FALSE) {
      bottom_temp <- covariate_data$Temp_C[row]
      max_depth <- covariate_data$Depth_m[row]
      stratified <- if_else(surface_temp - bottom_temp > 2, "TRUE", "FALSE")
    }
    if (row == nrow(covariate_data)) {
      stratify_zm[i,1] <- temp_site
      stratify_zm[i,2] <- if_else(surface_temp - bottom_temp > 2, "TRUE", "FALSE")
      stratify_zm[i,3] <- max_depth
    }
  }
}
#stratify_zm %>% slice(3:8) %>% gt::gt()
clean_covariates <- merge(covariate_data, stratify_zm, by = "UID")

# This is the data frame with one column per lake sample visit, we lose some information (temperature/DO at depth) but has most data.
clean_covariates <- clean_covariates %>% 
  dplyr::filter(Depth_m == 0) %>% 
  dplyr::select(-max_depth) %>%
  mutate(Code = str_extract(UID, "[aA-zZ]+"))

rm(stratify_zm); rm(covariate_data)
```

```{r mean_depth}
'# Takes in hypsography data and calulates mean depth

depth_files <- list.files("./data/hypsography/", pattern = "*.csv")
df_list <- sapply(paste0("./data/hypsography/" ,depth_files), read_csv, simplify = FALSE)
attr(df_list, "names") <- depth_files

depth_df <- bind_rows(df_list, .id = "df_list")
depth_df$depths = depth_df$depths * .3048
mean_depth_df <- data.frame(ID = character(), mean_depth = numeric())
for (i in 1:length(unique(depth_df$df_list))){
  print(i)
  temp <- depth_df %>% dplyr::filter(df_list == unique(depth_df$df_list)[i])
  volume <- MESS::auc(temp$areas, temp$depths, type = "spline")
  mean_depth = as.numeric(volume/temp[1,3])
  mean_depth_df[i, ] = c(temp[1,1], mean_depth*3.28)
}

# outputs a df with mean_depth '
```

```{r lake, warning = FALSE}
# merges the profile/WQ data with the lake physical data

lakesitecovariates <- merge(physical, clean_covariates, by = c("Lake","Code"))
lakesitecovariates <- lakesitecovariates %>%
  mutate(
         Lake = as.factor(Lake),
         visit_number = as.factor(visit_number),
         DOW = as.factor(DOW),
         mean_depth_ft = as.numeric(mean_depth_ft),
         UID = as.factor(UID),
         cond = as.numeric(cond),
         pH = as.numeric(pH),
         Clarity_m = as.numeric(Clarity_m))
```

```{r mergeqpcr}
# removes/changes some things with PCR data and merges it with covariate data
field_lab_blanks <- qpcr_data %>% 
  mutate(visit_number = substr(str_extract(uid, "[0-9]+"), 1, 1),
         visit_site = as.numeric(substr(str_extract(uid, "[0-9]+"), 2, 4)),
         Code = str_extract(uid, "[aA-zZ]+"),
         row = str_c(Code, visit_number, target)) %>%
  dplyr::filter(Code != "SLEX") %>%
  dplyr::filter(visit_site == 0 | visit_site == 11 | visit_site == 12) %>%
  dplyr::filter(sq_mean > .5) %>%
  #dplyr::filter(visit_site == 0 | visit_site == 12) %>%
  distinct(uid, target, .keep_all = T)

subset_qpcr_data <- qpcr_data %>%
  mutate(visit_number = substr(str_extract(uid, "[0-9]+"), 1, 1),
         visit_site = as.numeric(substr(str_extract(uid, "[0-9]+"), 2, 4)),
         Code = str_extract(uid, "[aA-zZ]+")) %>%
  dplyr::filter(Code != "PKEX", Code != "SLEX") %>%
  dplyr::filter(visit_site > 0, visit_site < 11)

subset_qpcr_data %>% group_by(Code, visit_number) %>%
  count(uid) %>%
  summarise(n = n())

all_data_pcr <- merge(subset_qpcr_data, lakesitecovariates, 
                      by = c("Code", "visit_number"))

finishedpcr <- all_data_pcr %>% distinct(visit_number, Code, target) %>%
  count(Code) #How many lake-visits do we have qpcr data for?
```


```{r formatting}
detection_data <- all_data_pcr %>%
  mutate(sq = ifelse(is.na(sq), 0, sq),
         sq_mean = ifelse(is.na(sq_mean), 0, sq_mean),
         pres_abs = ifelse(sq > 1, 1, 0)) %>%
  dplyr::select(!c("sq", "sq_mean", "sq_sd", "UID", "Notes", "Depth_m", "Team", "County")) %>%
  # removes copy number and unneeded stuff
  mutate(site = as.factor(paste0(Code, "_", visit_number)),
         sample = as.numeric(substr(str_extract(uid, "[0-9]+"), 2, 3)),
         row = str_c(Code, visit_number, target)) %>%
  pivot_wider(names_from = replicate, values_from = pres_abs) %>% 
  #dplyr::filter(Code != "OWA") %>%
  rename(UID = "uid")

#sample level covariates. Launch, Deep point, depth etc
eDNAsample_data <- sample_data %>% 
  filter(Type == "eDNA") %>%
  mutate(deep = ifelse(deep == "Yes", T, F),
         launch = ifelse(launch == "Yes", T, F),
         nearshore = ifelse(Habitat == "Nearshore", T, F),
         depth_m = as.numeric(depth_m)) %>%
  dplyr::select(UID, nearshore, deep, launch, depth_m) 

detection_data <- merge(eDNAsample_data, detection_data , by = "UID", all.y = T)


detection_data <- detection_data %>% 
  relocate(UID, sample, visit_number, target, pcr_1, pcr_2,pcr_3)

temp <- detection_data %>% distinct(Date, Code,  .keep_all = T)

rm(all_data_pcr); rm(eDNAsample_data)
rm(subset_qpcr_data);rm(lakesitecovariates)
```



```{r contamination}
contamination <- detection_data %>%
  mutate(contaminated = as.factor(ifelse(row %in% field_lab_blanks$row, 1, 0)))

contamination <- contamination %>%
  rowwise() %>%
  mutate(numdetection = sum(c_across(pcr_1:pcr_3)),
         numdetection = ifelse(numdetection == 0, 0, 1),
         mixed_to_bottom = ifelse(depth_m < strat_zm, TRUE, FALSE),
         julian_day = yday(Date),
         visit_site = as.factor(visit_site),
         visit_number = as.numeric(visit_number),
         lake_site = str_c(Code, visit_site),
         target = as.factor(target),
         depth_m = log(depth_m),
         area_acres = log(area_acres),
         littoral_area_acres = log(littoral_area_acres)) 

dates <- contamination$julian_day #save for later :)
depths <- contamination$depth_m

plot <- contamination

contamination[c("depth_m", "Clarity_m", "julian_day", "area_acres", "pH",
              "littoral_area_acres", "max_depth_ft", "mean_depth_ft", "strat_zm", "cond")] <-
  lapply(contamination[c("depth_m", "Clarity_m", "julian_day", "area_acres", "pH",
                       "littoral_area_acres","max_depth_ft", "mean_depth_ft", "strat_zm", "cond")],
         function(x) scale(x))
```


# plots for exploration
```{r}
#which lakes have new detections
newdetections_cc <- contamination %>%
  dplyr::filter(CC ==0) %>%
  dplyr::filter(numdetection > 0) %>%
  dplyr::filter(target == "common carp") %>% 
  dplyr::filter(!Code %in% c("VER", "SHG"))

newdetections_rc <- contamination %>%
  dplyr::filter(RC == 0) %>%
  dplyr::filter(numdetection > 0) %>%
  dplyr::filter(target == "Crayfish") %>% 
  dplyr::filter(!Code %in% c()) %>%
  dplyr::filter(contaminated == 0)

plot %>% 
  group_by(julian_day, Code, target) %>%
  mutate(numdetection = as.numeric(numdetection),
         julian_day = as.Date(julian_day, origin = as.Date("2021-01-01"))) %>%
  #dplyr::filter(target != "ZebraMussel") %>%
  summarise(detections = sum(as.numeric(numdetection)), visit_number, contaminated) %>%
  ggplot() +
  labs(y = "Positive Detections per Lake-Visit", x = "Day of Year", title = "2021") +
  geom_point(aes(y = detections, x = julian_day, color = contaminated), inherit.aes = F) +
  #geom_smooth(aes(y = detections, x = julian_day)) +
  geom_smooth(aes(y = detections, x = julian_day, color = contaminated)) +
  facet_wrap(vars(target)) +
  #scale_x_date(date_breaks = "1 month", date_labels =  "%b") +
  theme(plot.title = element_text(hjust = 0.5, size = 16), 
        axis.title.x = element_text(size = 16),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16))


plot %>% #dplyr::filter(Code != "LEH") %>% dplyr::filter(Code != "BEN") %>%
  group_by(julian_day, Lake, target, Clarity_m, strat_zm, pH, cond, mean_depth_ft) %>%
  #dplyr::filter(contaminated == 0) %>%
  mutate(numdetection = as.numeric(numdetection),
         julian_day = as.Date(julian_day, origin = as.Date("2021-01-01"))) %>%
  dplyr::filter( target == "Crayfish") %>%
  summarise(detections = sum(as.numeric(numdetection)), visit_number) %>%
  ggplot() +
  labs(y = "Positive Detections per Lake-Visit") +
  geom_point(aes(y = detections, x = julian_day, color = Lake)) + 
  geom_smooth(aes(y = detections, x = julian_day)) +
  facet_wrap(vars(target)) +
  #scale_x_date(date_breaks = "1 month", date_labels =  "%b") +
  theme(plot.title = element_text(hjust = 0.5, size = 16), 
        axis.title.x = element_text(size = 16),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16))

#ggsave("./figures/detectionsWcontamWsmooth.jpg", width = 11, height = 9)
```


# Start of modelling. GAMS and GLMMs
```{r modelWOpcr}
library(lme4)
library(mgcv)

rc = contamination %>% dplyr::filter(target == "Crayfish") %>% 
  mutate(visit_number = as.factor(visit_number)) %>% 
  dplyr::filter(contaminated == 0)

carp = contamination %>% dplyr::filter(target == "common carp") %>% 
  mutate(visit_number = as.factor(visit_number)) %>%
  dplyr::filter(contaminated == 0)

'rand.gam <- gam(numdetection ~ depth_m + 
                  s(julian_day, m= 2) +
                  s(julian_day, Lake, bs = "fs", k = 6, m = 2),
                data = rc, method = "REML", family = nb())
summary(rand.gam)
plot(rand.gam)
k.check(rand.gam)'


rc_model <- glmer(numdetection ~ poly(julian_day, degree = 2) +
                       (1|Lake/sample), family = binomial, data = rc)
plot(rc_model)
qqnorm(residuals(rc_model))
summary(rc_model)
#plot(effects::allEffects(rc_model, residuals = T))
plot(effects::effect("julian_day", rc_model), type = "response")
plot(effects::effect("Clarity_m", rc_model), type = "response")
plot(effects::effect("depth_m", rc_model), type = "response")


plot(ranef(rc_model))


cc_model <- glmer(numdetection ~ poly(julian_day, degree = 2) + 
                       (1|Lake/sample), family = binomial, data = carp)
summary(cc_model)
plot(cc_model)
plot(effects::allEffects(cc_model, residuals = T))
plot(effects::effect("julian_day", cc_model), type = "response")
plot(effects::effect("Clarity_m", cc_model),type = "response")
plot(effects::effect("depth_m", cc_model), type = "response")
```

# Mixed eefects RF
```{r}
#https://github.com/randel/MixRF
library(MixRF)

mix_RF_df <- carp %>% drop_na() %>%
  mutate(numdetection = numdetection)

X <- mix_RF_df %>% dplyr::select(depth_m,julian_day, Temp_C, pH, cond, Clarity_m, 
                                 DO_mgL,strat_zm, stratified,area_acres,
                                 littoral_area_acres, max_depth_ft)


carp_mixeded <- MixRF(Y = mix_RF_df$numdetection, X = X, 
                 random = "(1|DOW/sample)", data = mix_RF_df, 
                 initialRandomEffects = 0, ErrorTolerance = 0.01, 
                 MaxIterations = 100)

print(carp_mixeded$forest)

varImpPlot(carp_mixeded$forest)

partialPlot(carp_mixeded$forest, as.data.frame(mix_RF_df), x.var = "depth_m")
partialPlot(carp_mixeded$forest, as.data.frame(mix_RF_df), x.var = "cond")

##### Rusty crayfish

mix_RF_df <- rc %>% drop_na() 


X <- mix_RF_df %>% dplyr::select(depth_m, julian_day, Temp_C, pH, cond, 
                                 Clarity_m, DO_mgL,strat_zm, stratified, 
                                 area_acres, littoral_area_acres, max_depth_ft)


mixeded <- MixRF(Y = mix_RF_df$numdetection, X = X, 
                 random = "(1|DOW/sample)", data = mix_RF_df, 
                 initialRandomEffects = 0, ErrorTolerance = 0.1, 
                 MaxIterations = 100)

print(mixeded$forest)

varImpPlot(mixeded$forest)

rc_forest <- mixeded$forest

partialPlot(rc_forest, as.data.frame(mix_RF_df), x.var = "depth_m")
partialPlot(rc_forest, as.data.frame(mix_RF_df), x.var = "cond")

```

# stable
```{r stable}
Sys.setenv(JAGS_HOME = 'C:/Program Files')
library(jagsUI)

# these are the lakes with all 5 PCR visits
data4jags <- contamination %>% 
  mutate(julian_day_2 = julian_day^2) %>%
  #dplyr::filter(contaminated == 0) %>%
  dplyr::filter(
    Code %in% c("BDG", "BEN", "CLR", "FLF", "FST", "ILR", "KAB", "LEH", "MIL", "OWA", "OWS",
                "PHN", "PKE", "PRO", "SHG", "TEN", "VER", "WHB")) %>%
  dplyr::filter(target %in% c("common carp", "Crayfish")) %>%
  relocate(Code, UID, visit_number, sample, target, pcr_1, pcr_2, 
           pcr_3, depth_m, area_acres, julian_day, julian_day_2, contaminated) %>%
  arrange(target, Code, visit_number, sample)

n.lakes <- as.numeric(length(unique(data4jags$Code)))
n.sites <- 10
n.spp <- 2

carp_visits <- data4jags %>%
  dplyr::filter(target == "common carp") %>%
  distinct(Code, target, visit_number) %>%
  count(Code) %>% 
  arrange(Code)
crayfish_visits <- data4jags %>%
  dplyr::filter(target == "Crayfish") %>%
  distinct(Code, target, visit_number) %>%
  count(Code) %>% 
  arrange(Code)

visits = cbind(crayfish_visits[,2], carp_visits[,2])

occupancy <- matrix( c(1,1,
                       1,1,
                       1,1,
                       0,0,
                       1,1,
                       0,0,
                       1,1,
                       1,1,
                       1,1,
                       1,1,
                       1,1,
                       1,1,
                       0,0,
                       1,1,
                       1,1,
                       1,0,
                       1,1,
                       1,1), ncol = 2, byrow = T)

# covraiate for depth
depth.data <- data4jags %>% group_by(Code, visit_site) %>%
  mutate(site_depth_m = mean(depth_m)) %>%
  distinct(Code, visit_site, site_depth_m) %>%
  pivot_wider(names_from = "visit_site", values_from = site_depth_m) %>%
  remove_rownames %>% column_to_rownames(var = "Code")
# covariate for julian day
jd.data <- data4jags %>% group_by(Code, visit_number) %>%
  distinct(Code, visit_number, julian_day) %>%
  pivot_wider(names_from = "visit_number", values_from = julian_day) %>%
  remove_rownames %>% column_to_rownames(var = "Code")
# covariate for julian day^2
jd2.data <- data4jags %>% group_by(Code, visit_number) %>%
  mutate(julian_day = julian_day^2) %>%
  distinct(Code, visit_number, julian_day) %>%
  pivot_wider(names_from = "visit_number", values_from = julian_day) %>%
  remove_rownames %>% column_to_rownames(var = "Code")

area.acres <- data4jags %>% group_by(Code) %>%
  dplyr::select(area_acres) %>%
  distinct(Code, area_acres) %>%
  pivot_wider(names_from = "Code", values_from = area_acres) 

stratified <- data4jags %>% group_by(Code, visit_number) %>%
  dplyr::select(stratified) %>%
  distinct(Code, visit_number, stratified) %>%
  mutate(stratified = ifelse(stratified == T, 1, 0)) %>%
  pivot_wider(names_from = "visit_number", values_from = stratified) %>%
  remove_rownames %>% column_to_rownames(var = "Code")

species <- data4jags %>% mutate(species = ifelse(target == "Crayfish", 1, 2)) %>%
  dplyr::select(species)

lake <- data4jags %>% ungroup() %>% mutate(lake_number =
  case_when(
  Code == "BDG" ~ 1, 
  Code == "BEN" ~ 2,
  Code == "CLR" ~ 3,
  Code == "FLF" ~ 4,
  Code == "FST" ~ 5,
  Code == "ILR" ~ 6,
  Code == "KAB" ~ 7,
  Code == "LEH" ~ 8,
  Code == "MIL" ~ 9,
  Code == "OWA" ~ 10,
  Code == "OWS" ~ 11,
  Code == "PHN" ~ 12,
  Code == "PKE" ~ 13,
  Code == "PRO" ~ 14,
  Code == "SHG" ~ 15,
  Code == "TEN" ~ 16,
  Code == "VER" ~ 17,
  Code == "WHB" ~ 18)) %>% dplyr::select(lake_number)

jags.data.temp <- list(y = as.matrix(data4jags[,6:8]), 
                  n.obs = nrow(data4jags),
                  n.spp = n.spp, n.lakes = n.lakes,
                  visits = visits,
                  n.sites = 10, n.times = 5, 
                  n.reps = 3, occupancy = occupancy,
                  spp = as.vector(species[,1]), lake = as.matrix(lake[,1]),
                  time = data4jags[,3], site = data4jags[,4],
                  depth = as.matrix(depth.data), 
                  julian_day = as.matrix(data4jags[,11]), 
                  julian_day2 = as.matrix(data4jags[,12]),
                  jd = jd.data, jd2 = jd2.data, lake.size = area.acres)

occupancy = as.matrix(occupancy)


sink("eDNA_occ.txt")
cat("
model {
# priors
  # regression coefficients
  
  # SD's for simple random effects (detection: p)
  psi.spp.sd ~ dunif(0, 1) # SD for spp effects
  psi.spp.tau <- pow(psi.spp.sd, -2) # convert to precision
  psi.lake.sd ~ dunif(0, 1) # SD for lake effects
  psi.lake.tau <- pow(psi.lake.sd, -2) 
  # sites are uniquely nested within lakes, no context as simple RE

  # SDs and precision for complex random effects (all presumed spp-specific)
  psi.spp.lake.sd ~ dunif(0, 1) # spp-lake effect
  psi.spp.lake.tau <- pow(psi.spp.lake.sd, -2) 
  psi.spp.lake.site.sd ~ dunif(0, 1) # SD for site effects within lakes within spp
  psi.spp.lake.site.tau <- pow(psi.spp.lake.site.sd, -2) 

# species specific priors 
  for (i in 1:n.spp){
    psi.spp[i] ~ dunif(0, 1) # species-specific occupancy
    b.depth[i] ~ dnorm(0, 0.33) # vague prior for regression slope of depth
    b.lake.size[i] ~ dnorm(0, 0.33)
    
    p.spp[i] ~ dnorm(0, 1.75)  # spp mean detection (logit scale)
    a.jd[i] ~ dnorm(0, 0.33)
    a.jd2[i] ~ dnorm(0, 0.33)
    
    # species-lake effect
    for (j in 1:n.lakes){
      psi.spp.lake[i,j] ~ dnorm(0, psi.spp.lake.tau) # lake-by-spp adjustments
      for (s in 1:n.sites){
        psi.spp.lake.site[i,j,s] ~ dnorm(0, psi.spp.lake.site.tau) # spp-lake-site
      }
    }
  }

# Ecological model for true detection (occupancy)

  for (i in 1:n.spp) {
    for (j in 1:n.lakes){
        for (s in 1:n.sites){
          logit(psi[i,j,s]) <- psi.spp[i] + psi.spp.lake[i,j] + psi.spp.lake.site[i,j,s] +
            b.depth[i] * depth[j,s] + b.lake.size[i] * lake.size[,j]
            
        } # end site loop (i)
    } # end spp loop (j)
  } # end spp loop (i)

# Observation model for replicated detection/nondetection observations (detection)

    for (n in 1:n.obs) {
      z[n] <- occupancy[lake[n,],spp[n,]] # is the species in the lake?
      for (k in 1:n.reps){
        logit(p[n, k]) <- p.spp[spp[n,]] + a.jd[spp[n,]] * julian_day[n,] + 
                                a.jd2[spp[n,]] * julian_day2[n,]
        
        y[n,k] ~ dbern(z[n]*psi[spp[n,],lake[n,],site[n,]]*(p[n, k])) 
        
        # is the species in the lake * which species, which lake, what time, what site
      } # close k
    } # close n
    
} # end jags model
",fill = TRUE)  # back to R code
sink()

# Parameters monitored
params <- c("b.depth", "b.lake.size", "a.jd", "a.jd2",
            "p.spp", "psi.spp", "psi.spp.sd", 
            "psi.spp.lake", "psi.lake.sd", 
            "psi.spp.lake.sd", "psi.spp.lake.sd")

na <- 1000; ni <- 5000; nt <- 3; nb <- 1000; nc <- 3 # short for test run
#na <- 1000; ni <- 60000; nt <- 10; nb <- 10000; nc <- 3

# Call JAGS from R (~44 min at 60,000 ni)
eDNA1.out <- jags(jags.data.temp, inits = NULL, params, "eDNA_occ.txt", 
                  n.adapt = na, n.chains = nc, n.thin = nt, 
                  n.iter = ni, n.burnin = nb, parallel = TRUE)
print(eDNA1.out, dig = 2)
mcmcOutput::diagPlot(eDNA1.out)
plogis(eDNA1.out$mean$psi.spp.lake)

par(mfrow = c(2,2))
# crayfish = red
plot(density(eDNA1.out$sims.list$b.depth[,1]), xlim = c(-1,1), 
     xlab = "Parameter estimate", main = "Depth effect")
abline(v = eDNA1.out$mean$b.depth[1], col = "red")
plot(density(eDNA1.out$sims.list$b.depth[,2]), xlim = c(-1,1), 
     xlab = "Parameter estimate", main = "Depth effect")
abline(v = eDNA1.out$mean$b.depth[2], col = "green")
plot(density(eDNA1.out$sims.list$a.jd[,1]), xlim = c(-1,2), 
     xlab = "Parameter estimate", main = "Julian day effect")
abline(v = eDNA1.out$mean$a.jd[1], col = "red")
plot(density(eDNA1.out$sims.list$a.jd[,2]), xlim = c(-1,2), 
     xlab = "Parameter estimate", main = "Julian day effect")
abline(v = eDNA1.out$mean$a.jd[2], col = "green")

par(mfrow = c(1,2))
plot(density(eDNA1.out$sims.list$psi.spp.lake.sd), xlim = c(0,2), 
     xlab = "Parameter estimate", main = "Species-lake effect")
abline(v = eDNA1.out$meanspp_lake.sd, col = "red")

plot(density(eDNA1.out$sims.list$psi.lake.sd), xlim = c(0,1), 
     xlab = "Parameter estimate", main = "Lake effect")
abline(v = eDNA1.out$meanlake.sd, col = "red")

# Detection probability for each species by lake
plot(1:n.lakes, plogis(eDNA1.out$mean$psi.spp[1] + eDNA1.out$mean$psi.spp.lake[1,]), 
     pch = 19, type = 'b', ylim = c(0,1), ylab = "Detection probability", 
     xlab = "Lake number", main = "Model estimates")
for (i in 2:n.spp){
  points(1:n.lakes, plogis(eDNA1.out$mean$psi.spp[i] + eDNA1.out$mean$psi.spp.lake[i,]), 
       pch = 19, type = 'b', col = i) 
}



eDNA1.out$mean$p.spp.lake.site[1,,1] # Species 1, site 1
eDNA1.out$mean$p.spp.lake.site[1,1,] # Species 1, lake 1


tidy.output <- data.frame(mean = numeric(), spp = numeric(), lake = numeric(), site = numeric())
num = 1
for (i in 1:n.spp){
  for (j in 1:n.lakes){
    for (k in 1:n.sites){
      tidy.output[num,] <- data.frame(mean = eDNA1.out$mean$psi.spp.lake.site[i,j,k], 
                                      spp = i, lake = j, site = k)
      num = num + 1
    }
  }
}


tidy.output %>% 
  mutate(prob.mean = plogis(mean), ssp = as.factor(spp), lake = as.factor(lake), site = as.factor(site)) %>%
  ggplot(aes(x = site, y = prob.mean, color = lake, group = lake)) +
  #geom_point() +
  geom_line() +
  facet_wrap(vars(spp))
ggsave("jags.site.variability.png")


# plot depth effect over time 
range(contamination$depth_m, na.rm = T)
depth_pred <- seq(1, 80, by = 0.5)
log_depth_pred <- log(depth_pred)
depth.standard <- wiqid::standardize2match(log_depth_pred, depths)

depthplot <- matrix(NA, 80*n.spp, 3)

depthplot <- data.frame( depth =  rep(depth_pred, n.spp),
                     depth.standard = rep(depth.standard, n.spp), 
                     depth.standard2 = rep(depth.standard^2, n.spp),
                     mean = rep(NA, length(depth.standard)*2), 
                     high = rep(NA, length(depth.standard)*2), 
                     low = rep(NA, length(depth.standard)*2), 
                     spp = as.factor(c(rep(1, length(depth.standard)), rep(2, length(depth.standard)))))

for (i in 1:nrow(depthplot)) {
  s = depthplot[i,7]
  # I should be adding an intercept here?
  logit.p.tmp <- eDNA1.out$sims.list$b.depth[,s] * depthplot$depth.standard[i] + eDNA1.out$sims.list$psi.spp[,s]
    
    #with(eDNA1.out$sims.list, b.jd * dates.standard[i] + b.jd2 * dates.standard[i]^2)
  p.tmp <- plogis(logit.p.tmp)
  depthplot[i, 4] <- mean(p.tmp)
  depthplot[i, 5:6] <- HDInterval::hdi(p.tmp)
}

depthplot %>%
  ggplot(aes(x = depth, y = mean, color = spp)) +
  geom_line() +
  geom_ribbon(aes(ymin = low, ymax = high, fill = spp), alpha = 0.2)
#ggsave("jags.deptheffect.png")






range(contamination$julian_day)
dates_pred <- seq(105, 300)
dates.standard <- wiqid::standardize2match(dates_pred, dates)

jdplot <- matrix(NA, 196*n.spp, 3)

jdplot <- data.frame( dates =  rep(dates_pred, n.spp),
                     dates.standard = rep(dates.standard, n.spp), 
                     dates.standard2 = rep(dates.standard^2, n.spp),
                     mean = rep(NA, length(dates_pred)*2), 
                     high = rep(NA, length(dates_pred)*2), low = rep(NA, length(dates_pred)*2), 
                     spp = as.factor(c(rep(1, length(dates_pred)), rep(2, length(dates_pred)))))

for (i in 1:nrow(jdplot)) {
  s = jdplot[i,7]
  # I should be adding an intercept here?
  logit.p.tmp <- eDNA1.out$sims.list$a.jd[,s] * jdplot$dates.standard[i] + 
      eDNA1.out$sims.list$a.jd2[,s] * jdplot$dates.standard2[i] + eDNA1.out$sims.list$p.spp[,s]
    
    #with(eDNA1.out$sims.list, b.jd * dates.standard[i] + b.jd2 * dates.standard[i]^2)
  p.tmp <- plogis(logit.p.tmp)
  jdplot[i, 4] <- mean(p.tmp)
  jdplot[i, 5:6] <- HDInterval::hdi(p.tmp)
}

jdplot %>%
  ggplot(aes(x = dates, y = mean, color = spp)) +
  geom_line() +
  geom_ribbon(aes(ymin = low, ymax = high, fill = spp), alpha = 0.2)+
  labs(y = "Detection probability", x = "Julian day")
#ggsave("jags.juliandayeffect.png")

```


# Adding the ability to skip contaminated samples
```{r}
Sys.setenv(JAGS_HOME='C:/Program Files')
library(jagsUI)

# these are the lakes with all 5 PCR visits
data4jags <- contamination %>% 
  mutate(julian_day_2 = julian_day^2) %>%
  dplyr::filter(
    Code %in% c("BDG", "BEN", "CLR", "FLF", "FST", "ILR", "KAB", "LEH", "MIL", "OWA", "OWS",
                "PHN", "PKE", "PRO", "SHG", "TEN", "VER", "WHB")) %>%
  relocate(Code, UID, visit_number, sample, target, pcr_1, pcr_2, 
           pcr_3, depth_m, area_acres, julian_day, julian_day_2) %>%
  arrange(target, Code, sample, visit_number) %>%
  dplyr::filter(contaminated != 1)

# What lakes are we missing adding ILR, KAB, OWA, PKE 
#MCN, JHN, SHG, ILR, VER, PKE, CRN, KAB, OWA

n.lakes <- as.numeric(length(unique(data4jags$Code)))
n.sites <- 10
n.spp <- 2

occupancy <- matrix( c(1,1,
                       1,1,
                       1,1,
                       0,0,
                       1,1,
                       0,0,
                       1,1,
                       1,1,
                       1,1,
                       1,1,
                       1,1,
                       1,1,
                       0,0,
                       1,1,
                       1,1,
                       1,0,
                       1,1,
                       1,1), ncol = 2, byrow = T)


#occupancy1 <- matrix(c(0,0,0), c(,1,1,1), ncol = 2, byrow = T)
rownames(occupancy) <- c("BDG", "BEN", "CLR", "FLF", "FST", "ILR", "KAB", "LEH", 
                         "MIL", "OWA", "OWS","PHN", "PKE", "PRO", "SHG", "TEN", "VER", "WHB")
colnames(occupancy) <- c("RC", "CC")
# covraiate for depth
depth.data <- data4jags %>% dplyr::select(depth_m)
# covariate for julian day
jd.data <- data4jags %>% dplyr::select(julian_day)
# covariate for julian day^2
jd2.data <- data4jags %>% mutate(jd2 = julian_day^2) %>% dplyr::select(jd2)

area.acres <- data4jags %>% dplyr::select(area_acres)

species <- data4jags %>% mutate(species = ifelse(target == "Crayfish", 1, 2)) %>%
  dplyr::select(species)

lake <- data4jags %>% ungroup() %>% mutate(lake_number =
  case_when(
  Code == "BDG" ~ 1, 
  Code == "BEN" ~ 2,
  Code == "CLR" ~ 3,
  Code == "FLF" ~ 4,
  Code == "FST" ~ 5,
  Code == "ILR" ~ 6,
  Code == "KAB" ~ 7,
  Code == "LEH" ~ 8,
  Code == "MIL" ~ 9,
  Code == "OWA" ~ 10,
  Code == "OWS" ~ 11,
  Code == "PHN" ~ 12,
  Code == "PKE" ~ 13,
  Code == "PRO" ~ 14,
  Code == "SHG" ~ 15,
  Code == "TEN" ~ 16,
  Code == "VER" ~ 17,
  Code == "WHB" ~ 18)) %>% dplyr::select(lake_number)

jags.data.temp <- list(y = as.matrix(data4jags[,6:8]), 
                  n.obs = nrow(data4jags),
                  n.spp = n.spp, n.lakes = n.lakes,
                  n.sites = 10, n.times = 5, 
                  n.reps = 3, occupancy = occupancy,
                  spp = as.vector(species[,1]), lake = as.matrix(lake[,1]),
                  time = data4jags[,3], site = data4jags[,4],
                  depth = as.matrix(depth.data), 
                  julian_day = as.matrix(data4jags[,11]), 
                  julian_day2 = as.matrix(data4jags[,12]),
                  jd = jd.data, jd2 = jd2.data, lake.size = area.acres)

occupancy = as.matrix(occupancy)


sink("eDNA_occ.txt")
cat("
model {
# priors
  # regression coefficients
  
  # SD's for simple random effects (detection: p)
  psi.spp.sd ~ dunif(0, 1) # SD for spp effects
  psi.spp.tau <- pow(psi.spp.sd, -2) # convert to precision
  psi.lake.sd ~ dunif(0, 1) # SD for lake effects
  psi.lake.tau <- pow(psi.lake.sd, -2) 
  # sites are uniquely nested within lakes, no context as simple RE

  # SDs and precision for complex random effects (all presumed spp-specific)
  psi.spp.lake.sd ~ dunif(0, 1) # spp-lake effect
  psi.spp.lake.tau <- pow(psi.spp.lake.sd, -2) 
  psi.spp.lake.site.sd ~ dunif(0, 1) # SD for site effects within lakes within spp
  psi.spp.lake.site.tau <- pow(psi.spp.lake.site.sd, -2) 

# species specific priors 
  for (i in 1:n.spp){
    psi.spp[i] ~ dunif(0, 1) # species-specific occupancy
    b.depth[i] ~ dnorm(0, 0.33) # vague prior for regression slope of depth
    b.lake.size[i] ~ dnorm(0, 0.33)
    
    p.spp[i] ~ dnorm(0, psi.spp.tau)  # spp mean detection (logit scale)
    a.jd[i] ~ dnorm(0, 0.33)
    a.jd2[i] ~ dnorm(0, 0.33)
    
    # species-lake effect
    for (j in 1:n.lakes){
      psi.spp.lake[i,j] ~ dnorm(0, psi.spp.lake.tau) # lake-by-spp adjustments
      for (s in 1:n.sites){
        psi.spp.lake.site[i,j,s] ~ dnorm(0, psi.spp.lake.site.tau) # spp-lake-site
      }
    }
  }

# Ecological model for true detection (occupancy)

  for (i in 1:n.obs) {
          logit(psi[i]) <- psi.spp[spp[i,]] + psi.spp.lake[spp[i,], lake[i,]] + 
                            psi.spp.lake.site[spp[i,], lake[i,], site[i,]] +
                            b.depth[spp[i,]] * depth[i,] + b.lake.size[spp[i,]] * lake.size[i,]
  } # end obs loop (i)

# Observation model for replicated detection/nondetection observations (detection)

    for (n in 1:n.obs) {
      z[n] <- occupancy[lake[n,],spp[n,]] # is the species in the lake?
      for (k in 1:n.reps){
        logit(p[n, k]) <- p.spp[spp[n,]] + a.jd[spp[n,]] * julian_day[n,] + 
                                a.jd2[spp[n,]] * julian_day2[n,]
        
        y[n,k] ~ dbern(z[n]*psi[n]*(p[n, k])) 
        
        # is the species in the lake * which species, which lake, what time, what site
      } # close k
    } # close n
    
} # end jags model
",fill = TRUE)  # back to R code
sink()

# Parameters monitored
params <- c("b.depth", "b.lake.size", "a.jd", "a.jd2",
            "p.spp", "psi.spp", "psi.spp.sd", 
            "psi.spp.lake", "psi.lake.sd", 
            "psi.spp.lake.sd", "psi.spp.lake.sd")

na <- 2500; ni <- 5000; nt <- 3; nb <- 1000; nc <- 3 # short for test run
#na <- 1000; ni <- 60000; nt <- 10; nb <- 10000; nc <- 3

# Call JAGS from R (~44 min at 60,000 ni)
eDNA1.out <- jags(jags.data.temp, inits = NULL, params, "eDNA_occ.txt", 
                  n.adapt = na, n.chains = nc, n.thin = nt, 
                  n.iter = ni, n.burnin = nb, parallel = TRUE)
print(eDNA1.out, dig = 2)
mcmcOutput::diagPlot(eDNA1.out)

par(mfrow = c(2,2))
# crayfish = red
plot(density(eDNA1.out$sims.list$b.depth[,1]), xlim = c(-1,1), 
     xlab = "Parameter estimate", main = "Depth effect")
abline(v = eDNA1.out$mean$b.depth[1], col = "red")
plot(density(eDNA1.out$sims.list$b.depth[,2]), xlim = c(-1,1), 
     xlab = "Parameter estimate", main = "Depth effect")
abline(v = eDNA1.out$mean$b.depth[2], col = "green")
plot(density(eDNA1.out$sims.list$a.jd[,1]), xlim = c(-1,2), 
     xlab = "Parameter estimate", main = "Julian day effect")
abline(v = eDNA1.out$mean$a.jd[1], col = "red")
plot(density(eDNA1.out$sims.list$a.jd[,2]), xlim = c(-1,2), 
     xlab = "Parameter estimate", main = "Julian day effect")
abline(v = eDNA1.out$mean$a.jd[2], col = "green")

par(mfrow = c(1,2))
plot(density(eDNA1.out$sims.list$psi.spp.lake.sd), xlim = c(0,2), 
     xlab = "Parameter estimate", main = "Species-lake effect")
abline(v = eDNA1.out$meanspp_lake.sd, col = "red")

plot(density(eDNA1.out$sims.list$psi.lake.sd), xlim = c(0,1), 
     xlab = "Parameter estimate", main = "Lake effect")
abline(v = eDNA1.out$meanlake.sd, col = "red")

# Detection probability for each species by lake
plot(1:n.lakes, plogis(eDNA1.out$mean$psi.spp[1] + eDNA1.out$mean$psi.spp.lake[1,]), 
     pch = 19, type = 'b', ylim = c(0,1), ylab = "Detection probability", 
     xlab = "Lake number", main = "Model estimates")
for (i in 2:n.spp){
  points(1:n.lakes, plogis(eDNA1.out$mean$psi.spp[i] + eDNA1.out$mean$psi.spp.lake[i,]), 
       pch = 19, type = 'b', col = i) 
}


tidy.output %>% 
  mutate(prob.mean = plogis(mean), ssp = as.factor(spp), lake = as.factor(lake), site = as.factor(site)) %>%
  ggplot(aes(x = site, y = prob.mean, color = lake, group = lake)) +
  #geom_point() +
  geom_line() +
  facet_wrap(vars(spp))
ggsave("jags.site.variability.png")



#### plot depth effect for all species #### 
range(contamination$depth_m, na.rm = T)
(depth_pred <- seq(1, 80, by = 0.5))
log_depth_pred <- log(depth_pred)
depth.standard <- wiqid::standardize2match(log_depth_pred, depths)

depthplot <- matrix(NA, 80*n.spp, 3)

depthplot <- data.frame( depth =  rep(depth_pred, n.spp),
                     depth.standard = rep(depth.standard, n.spp), 
                     mean = rep(NA, length(depth.standard)*2), 
                     high = rep(NA, length(depth.standard)*2), low = rep(NA, length(depth.standard)*2), 
                     spp = as.factor(c(rep(1, length(depth.standard)), rep(2, length(depth.standard)))))

for (i in 1:nrow(depthplot)) {
  s = depthplot[i,6]
  # I should be adding an intercept here?
  logit.p.tmp <- eDNA1.out$sims.list$b.depth[,s] * depthplot$depth.standard[i] + eDNA1.out$sims.list$psi.spp[,s]
    
    #with(eDNA1.out$sims.list, b.jd * dates.standard[i] + b.jd2 * dates.standard[i]^2)
  p.tmp <- plogis(logit.p.tmp)
  depthplot[i, 3] <- mean(p.tmp)
  depthplot[i, 4:5] <- HDInterval::hdi(p.tmp)
}

depthplot %>%
  #dplyr::filter(spp == 1) %>%
  mutate(species = case_when(
    spp == 1 ~ "RC",
    spp == 2 ~ "CC"
  )) %>%
  ggplot(aes(x = depth, y = mean, color = species)) +
  geom_line() +
  labs(y = "DNA Occurence", x = "Julian day") +
  guides(color="none", fill = guide_legend("Species")) +
  geom_ribbon(aes(ymin = low, ymax = high, fill = species), alpha = 0.2)
#ggsave("jags.deptheffect.png")





#### Plot time effect for all species #####
range(contamination$julian_day)
dates_pred <- seq(105, 330)
dates.standard <- wiqid::standardize2match(dates_pred, dates)

jdplot <- matrix(NA, 196*n.spp, 3)

jdplot <- data.frame( dates =  rep(dates_pred, n.spp),
                     dates.standard = rep(dates.standard, n.spp), 
                     dates.standard2 = rep(dates.standard^2, n.spp),
                     mean = rep(NA, length(dates_pred)*2), 
                     high = rep(NA, length(dates_pred)*2), low = rep(NA, length(dates_pred)*2), 
                     spp = as.factor(c(rep(1, length(dates_pred)), rep(2, length(dates_pred)))))

for (i in 1:nrow(jdplot)) {
  s = jdplot[i,7]
  # I should be adding an intercept here?
  logit.p.tmp <- eDNA1.out$sims.list$a.jd[,s] * jdplot$dates.standard[i] + 
      eDNA1.out$sims.list$a.jd2[,s] * jdplot$dates.standard2[i] + eDNA1.out$sims.list$p.spp[,s]
    #with(eDNA1.out$sims.list, b.jd * dates.standard[i] + b.jd2 * dates.standard[i]^2)
  p.tmp <- plogis(logit.p.tmp)
  jdplot[i, 4] <- mean(p.tmp)
  jdplot[i, 5:6] <- HDInterval::hdi(p.tmp)
}

jdplot %>%
  mutate(species = case_when(
    spp == 1 ~ "RC",
    spp == 2 ~ "CC"
  )) %>%
  ggplot(aes(x = dates, y = mean, color = species)) +
  geom_line() +
  geom_ribbon(aes(ymin = low, ymax = high, x= dates, fill = species), alpha = 0.2) +
  labs(y = "Detection probability", x = "Julian day") +
  guides(color="none", fill = guide_legend("Species"))
#ggsave("jags.juliandayeffect.png")
```

# working on this
```{r}
Sys.setenv(JAGS_HOME = 'C:/Program Files')
library(jagsUI)

# these are the lakes with all 5 PCR visits
data4jags <- contamination %>% 
  mutate(julian_day_2 = julian_day^2) %>%
  dplyr::filter(contaminated == 0) %>%
  mutate(stratified = ifelse(stratified == T, 1, 2)) %>%
  dplyr::filter(
    Code %in% c("BDG", "BEN", "CLR", "FLF", "FST", "ILR", "KAB", "LEH", "MIL", "OWA", "OWS",
                "PHN", "PKE", "PRO", "SHG", "TEN", "VER", "WHB")) %>%
  dplyr::filter(target %in% c("common carp", "Crayfish")) %>%
  relocate(Code, UID, visit_number, sample, target, pcr_1, pcr_2, pcr_3, 
           depth_m, area_acres, julian_day, julian_day_2, stratified, contaminated) %>%
  arrange(target, Code, visit_number, sample)

n.lakes <- as.numeric(length(unique(data4jags$Code)))
n.sites <- 10
n.spp <- 2

carp_visits <- data4jags %>%
  dplyr::filter(target == "common carp") %>%
  distinct(Code, target, visit_number) %>%
  count(Code) %>% 
  arrange(Code)
crayfish_visits <- data4jags %>%
  dplyr::filter(target == "Crayfish") %>%
  distinct(Code, target, visit_number) %>%
  count(Code) %>% 
  arrange(Code)

visits = cbind(crayfish_visits[,2], carp_visits[,2])

occupancy <- matrix( c(1,1,
                       1,1,
                       1,1,
                       0,0,
                       1,1,
                       0,0,
                       1,1,
                       1,1,
                       1,1,
                       1,1,
                       1,1,
                       1,1,
                       0,0,
                       1,1,
                       1,1,
                       1,0,
                       1,1,
                       1,1), ncol = 2, byrow = T)

# covraiate for depth
depth.data <- data4jags %>% group_by(Code, visit_site) %>%
  mutate(site_depth_m = mean(depth_m)) %>%
  distinct(Code, visit_site, site_depth_m) %>%
  pivot_wider(names_from = "visit_site", values_from = site_depth_m) %>%
  remove_rownames %>% column_to_rownames(var = "Code")
# covariate for julian day

area.acres <- data4jags %>% group_by(Code) %>%
  dplyr::select(area_acres) %>%
  distinct(Code, area_acres) %>%
  pivot_wider(names_from = "Code", values_from = area_acres) 


species <- data4jags %>% mutate(species = ifelse(target == "Crayfish", 1, 2)) %>%
  dplyr::select(species)

lake <- data4jags %>% ungroup() %>% mutate(lake_number =
  case_when(
  Code == "BDG" ~ 1, 
  Code == "BEN" ~ 2,
  Code == "CLR" ~ 3,
  Code == "FLF" ~ 4,
  Code == "FST" ~ 5,
  Code == "ILR" ~ 6,
  Code == "KAB" ~ 7,
  Code == "LEH" ~ 8,
  Code == "MIL" ~ 9,
  Code == "OWA" ~ 10,
  Code == "OWS" ~ 11,
  Code == "PHN" ~ 12,
  Code == "PKE" ~ 13,
  Code == "PRO" ~ 14,
  Code == "SHG" ~ 15,
  Code == "TEN" ~ 16,
  Code == "VER" ~ 17,
  Code == "WHB" ~ 18)) %>% dplyr::select(lake_number)

jags.data.temp <- list(y = as.matrix(data4jags[,6:8]), 
                  n.obs = nrow(data4jags),
                  n.spp = n.spp, n.lakes = n.lakes,
                  visits = visits,
                  n.sites = 10, n.times = 5, 
                  n.reps = 3, occupancy = occupancy,
                  spp = as.vector(species[,1]), lake = as.matrix(lake[,1]),
                  time = data4jags[,3], site = data4jags[,4],
                  depth = as.matrix(depth.data), 
                  julian_day = as.matrix(data4jags[,11]), 
                  julian_day2 = as.matrix(data4jags[,12]),
                  strat = data4jags[,13], lake.size = area.acres)

occupancy = as.matrix(occupancy)


sink("eDNA_occ.txt")
cat("
model {
# priors

  # SDs and precision for complex random effects (all presumed spp-specific)
  psi.spp.lake.sd ~ dunif(0, 1) # spp-lake effect
  psi.spp.lake.tau <- pow(psi.spp.lake.sd, -2) 
  psi.spp.lake.site.sd ~ dunif(0, 1) # SD for site effects within lakes within spp
  psi.spp.lake.site.tau <- pow(psi.spp.lake.site.sd, -2) 

# species specific priors 
  for (i in 1:n.spp){
    psi.spp[i] ~ dunif(0, 1) # species-specific occupancy
    b.depth[i] ~ dnorm(0, 1.75) # vague prior for regression slope of depth
    b.lake.size[i] ~ dnorm(0, 1.75)
    
    #p.spp[i] ~ dnorm(0, 1.75)  # spp mean detection (logit scale)
    a.jd[i] ~ dnorm(0, 1.75)
    a.jd2[i] ~ dnorm(0, 1.75)
    
    for (status in 1:2){
    p.spp[i, status] ~ dnorm(0, 1.75)
    }
    
    # species-lake effect
    for (j in 1:n.lakes){
      psi.spp.lake[i,j] ~ dnorm(0, psi.spp.lake.tau) # lake-by-spp adjustments
      for (s in 1:n.sites){
        psi.spp.lake.site[i,j,s] ~ dnorm(0, psi.spp.lake.site.tau) # spp-lake-site
      }
    }
  }

# Ecological model for true detection (occupancy)

  for (i in 1:n.spp) {
    for (j in 1:n.lakes){
        for (s in 1:n.sites){
          logit(psi[i,j,s]) <- psi.spp[i] + psi.spp.lake[i,j] + psi.spp.lake.site[i,j,s] +
            b.depth[i] * depth[j,s] + b.lake.size[i] * lake.size[,j]
            
          # is the species in the lake * which species, which lake, what time, what site
        } # end site loop (i)
    } # end spp loop (j)
  } # end spp loop (i)

# Observation model for replicated detection/nondetection observations (detection)

    for (n in 1:n.obs) {
      z[n] <- occupancy[lake[n,],spp[n,]] # is the species in the lake?
      for (k in 1:n.reps){
        logit(p[n, k]) <- p.spp[spp[n,], strat[n,]] + a.jd[spp[n,]] * julian_day[n,] + 
                                a.jd2[spp[n,]] * julian_day2[n,]
        
        y[n,k] ~ dbern(z[n]*psi[spp[n,],lake[n,],site[n,]]*(p[n, k])) 
        
        
      } # close k
    } # close n
    
} # end jags model
",fill = TRUE)  # back to R code
sink()

# Parameters monitored
params <- c("b.depth", "b.lake.size", 
            "a.jd", "a.jd2", "a.strat",
            "p.spp", "psi.spp",
            "psi.spp.lake")

na <- 1000; ni <- 10000; nt <- 3; nb <- 1000; nc <- 3 # short for test run
#na <- 1000; ni <- 60000; nt <- 10; nb <- 10000; nc <- 3

# Call JAGS from R (~44 min at 60,000 ni)
eDNA1.out <- jags(jags.data.temp, inits = NULL, params, "eDNA_occ.txt", 
                  n.adapt = na, n.chains = nc, n.thin = nt, 
                  n.iter = ni, n.burnin = nb, parallel = TRUE)
print(eDNA1.out, dig = 2)
mcmcOutput::diagPlot(eDNA1.out)

par(mfrow = c(2,2))
# crayfish = red
plot(density(eDNA1.out$sims.list$b.depth[,1]), xlim = c(-1,1), 
     xlab = "Parameter estimate", main = "Depth effect")
abline(v = eDNA1.out$mean$b.depth[1], col = "red")
plot(density(eDNA1.out$sims.list$b.depth[,2]), xlim = c(-1,1), 
     xlab = "Parameter estimate", main = "Depth effect")
abline(v = eDNA1.out$mean$b.depth[2], col = "green")
plot(density(eDNA1.out$sims.list$a.jd[,1]), xlim = c(-1,2), 
     xlab = "Parameter estimate", main = "Julian day effect")
abline(v = eDNA1.out$mean$a.jd[1], col = "red")
plot(density(eDNA1.out$sims.list$a.jd[,2]), xlim = c(-1,2), 
     xlab = "Parameter estimate", main = "Julian day effect")
abline(v = eDNA1.out$mean$a.jd[2], col = "green")

par(mfrow = c(2,2))
# crayfish = red
plot(density(eDNA1.out$sims.list$a.strat[,1]), xlim = c(-3,3), 
     xlab = "Parameter estimate", main = "Depth effect")
abline(v = eDNA1.out$mean$a.strat[1], col = "red")
plot(density(eDNA1.out$sims.list$a.strat[,2]), xlim = c(-3,3), 
     xlab = "Parameter estimate", main = "Depth effect")
abline(v = eDNA1.out$mean$a.strat[2], col = "green")


par(mfrow = c(1,2))
plot(density(eDNA1.out$sims.list$psi.spp.lake.sd), xlim = c(0,2), 
     xlab = "Parameter estimate", main = "Species-lake effect")
abline(v = eDNA1.out$meanspp_lake.sd, col = "red")

plot(density(eDNA1.out$sims.list$psi.lake.sd), xlim = c(0,1), 
     xlab = "Parameter estimate", main = "Lake effect")
abline(v = eDNA1.out$meanlake.sd, col = "red")

# Occupancy probability for each species by lake
plot(1:n.lakes, plogis(eDNA1.out$mean$psi.spp[1] + eDNA1.out$mean$psi.spp.lake[1,]), 
     pch = 19, type = 'b', ylim = c(0,1), ylab = "Detection probability", 
     xlab = "Lake number", main = "Model estimates")
for (i in 2:n.spp){
  points(1:n.lakes, plogis(eDNA1.out$mean$psi.spp[i] + eDNA1.out$mean$psi.spp.lake[i,]), 
       pch = 19, type = 'b', col = i) 
}



eDNA1.out$mean$p.spp.lake.site[1,,1] # Species 1, site 1
eDNA1.out$mean$p.spp.lake.site[1,1,] # Species 1, lake 1


tidy.output <- data.frame(mean = numeric(), spp = numeric(), lake = numeric(), site = numeric())
num = 1
for (i in 1:n.spp){
  for (j in 1:n.lakes){
    for (k in 1:n.sites){
      tidy.output[num,] <- data.frame(mean = eDNA1.out$mean$psi.spp.lake.site[i,j,k], 
                                      spp = i, lake = j, site = k)
      num = num + 1
    }
  }
}


tidy.output %>% 
  mutate(prob.mean = plogis(mean), ssp = as.factor(spp), lake = as.factor(lake), site = as.factor(site)) %>%
  ggplot(aes(x = site, y = prob.mean, color = lake, group = lake)) +
  #geom_point() +
  geom_line() +
  facet_wrap(vars(spp))
ggsave("jags.site.variability.png")


# plot depth effect over time 
range(contamination$depth_m, na.rm = T)
depth_pred <- seq(1, 80, by = 0.5)
log_depth_pred <- log(depth_pred)
depth.standard <- wiqid::standardize2match(log_depth_pred, depths)

depthplot <- matrix(NA, 80*n.spp, 3)

depthplot <- data.frame( depth =  rep(depth_pred, n.spp),
                     depth.standard = rep(depth.standard, n.spp), 
                     depth.standard2 = rep(depth.standard^2, n.spp),
                     mean = rep(NA, length(depth.standard)*2), 
                     high = rep(NA, length(depth.standard)*2), 
                     low = rep(NA, length(depth.standard)*2), 
                     spp = as.factor(c(rep(1, length(depth.standard)), rep(2, length(depth.standard)))))

for (i in 1:nrow(depthplot)) {
  s = depthplot[i,7]
  # I should be adding an intercept here?
  logit.p.tmp <- eDNA1.out$sims.list$b.depth[,s] * depthplot$depth.standard[i] + eDNA1.out$sims.list$psi.spp[,s]
    
    #with(eDNA1.out$sims.list, b.jd * dates.standard[i] + b.jd2 * dates.standard[i]^2)
  p.tmp <- plogis(logit.p.tmp)
  depthplot[i, 4] <- mean(p.tmp)
  depthplot[i, 5:6] <- HDInterval::hdi(p.tmp)
}

depthplot %>%
  ggplot(aes(x = depth, y = mean, color = spp)) +
  geom_line() +
  geom_ribbon(aes(ymin = low, ymax = high, fill = spp), alpha = 0.2)
#ggsave("jags.deptheffect.png")



range(contamination$julian_day)
dates_pred <- seq(105, 300)
dates.standard <- wiqid::standardize2match(dates_pred, dates)

#jdplot <- matrix(NA, 196*n.spp, 3)

jdplot <- data.frame(dates =  rep(dates_pred, n.spp),
                     dates.standard = rep(dates.standard, n.spp), 
                     dates.standard2 = rep(dates.standard^2, n.spp),
                     mean = rep(NA, length(dates_pred)*2), 
                     high = rep(NA, length(dates_pred)*2), low = rep(NA, length(dates_pred)*2), 
                     spp = as.factor(c(rep(1, length(dates_pred)), rep(2, length(dates_pred)))))

for (i in 1:nrow(jdplot)) {
  s = jdplot[i,7]
  # I should be adding an intercept here?
  logit.p.tmp <- eDNA1.out$sims.list$a.jd[,s] * jdplot$dates.standard[i] + 
      eDNA1.out$sims.list$a.jd2[,s] * jdplot$dates.standard2[i] +
    eDNA1.out$sims.list$p.spp[,2,s]
  
  p.tmp <- plogis(logit.p.tmp)
  jdplot[i, 4] <- mean(p.tmp)
  jdplot[i, 5:6] <- HDInterval::hdi(p.tmp)
}

jdplot <- jdplot %>%
  mutate(species = case_when(
    spp == 1 ~ "RC",
    spp == 2 ~ "CC")) %>% 
  mutate(samples = detect.likeli(mean, .99),
                  samples.low = detect.likeli(low, .99),
                  samples.high = detect.likeli(high, .99))

jdplot %>%
  ggplot(aes(x = dates, y = mean, color = species)) +
  geom_line() +
  geom_ribbon(aes(ymin = low, ymax = high, x = dates, fill = species), alpha = 0.2) +
  labs(y = "Detection probability", x = "Julian day") +
  guides(color = "none", fill = guide_legend("Species"))

#ggsave("jags.juliandayeffect.png")

jdplot %>% 
  ggplot(aes(x = dates, y = samples, color = species)) +
  geom_line() +
  geom_ribbon(aes(ymin = samples.low, ymax = samples.high, fill = species), alpha = 0.2) +
  labs(y = "Number of samples required to get a \n95% Probability of detection", x = "Julian day") + 
  guides(color="none", fill = guide_legend("Species"))
  
plogis(eDNA1.out$mean$p.spp)

#p.spp[species, stratified = 1]

stratplot <- data.frame(
                     mean = rep(NA, n.spp)*2, 
                     high = rep(NA, n.spp*2), low = rep(NA, n.spp*2), 
                     species = as.factor(c(rep(1, n.spp), rep(2, n.spp))),
                     spp = as.factor(c(rep("RC", n.spp), rep("CC", n.spp))),
                     status = as.factor(c("Stratified", "Mixed")),
                     strat = as.factor(c(1, 2)))
for (i in 1:nrow(stratplot)){
  logit.p.strat.spp <- eDNA1.out$sims.list$p.spp[, stratplot$species[i], stratplot$strat[i]]
  p.tmp <- plogis(logit.p.strat.spp)
  stratplot[i, 1] <- mean(p.tmp)
  stratplot[i, 2:3] <- HDInterval::hdi(p.tmp)
}

stratplot %>%
  ggplot() +
  geom_boxplot(aes(x = status, y = mean, fill = spp))


```


```{r}
Sys.setenv(JAGS_HOME = 'C:/Program Files')
library(jagsUI)

lakes = c("BDG", "BEN", "CLR", "FLF", "FST", "ILR", "KAB", "LEH", "MIL", "OWA", "OWS",
                "PHN", "PKE", "PRO", "SHG", "TEN", "VER", "WHB")
species = c("common carp", "Crayfish")
n.lakes <- as.numeric(length(unique(data4jags$Code)))
n.sites <- 10
n.spp <- 2
unique.sites <- n.lakes*10

# these are the lakes with all 5 PCR visits
data4jags <- contamination %>% 
  mutate(julian_day_2 = julian_day^2) %>%
  dplyr::filter(contaminated == 0) %>%
  mutate(stratified = ifelse(stratified == T, 1, 0)) %>%
  dplyr::filter(
    Code %in% c("BDG", "BEN", "CLR", "FLF", "FST", "ILR", "KAB", "LEH", "MIL", "OWA", "OWS",
                "PHN", "PKE", "PRO", "SHG", "TEN", "VER", "WHB")) %>%
  dplyr::filter(target %in% c("common carp", "Crayfish")) %>%
  relocate(Code, UID, visit_number, sample, target, pcr_1, pcr_2, pcr_3, 
           depth_m, area_acres, julian_day, julian_day_2, stratified, contaminated) 

 
y.cc = data.frame(Code = rep(lakes, each = 10), sample = rep(1:10, times = 18),
               CC_1 = NA, CC_2 = NA, CC_3 = NA, 
               CC_4 = NA, CC_5 = NA)
y.rc = data.frame(Code = rep(lakes, each = 10), sample = rep(1:10, times = 18),
               RC_1 = NA, RC_2 = NA, RC_3 = NA, 
               RC_4 = NA, RC_5 = NA)



for (s in 1:length(species)) {
  for (l in 1:length(lakes)) {
    crayfish_lake = data4jags %>% dplyr::filter(Code == lakes[l] & target == species[s]) %>%
      arrange(visit_number)
    visits = 1:5
    for (v in 1:length(visits)){
      for (num in 1:10){
        temp = crayfish_lake %>% dplyr::filter(visit_number == visits[v] & sample == num) %>%
          select(numdetection)
        if (nrow(temp) == 0){
          temp = NA
        }
        if (species[s] == "common carp"){
          y.cc[y.cc$Code == lakes[l] & y.cc$sample == num, v + 2] = temp
        } else{
          y.rc[y.rc$Code == lakes[l] & y.rc$sample == num, v + 2] = temp
        }
      }
    }
  }
}
y = list(rc = y.rc, cc = y.cc)

carp_visits <- data4jags %>%
  dplyr::filter(target == "common carp") %>%
  distinct(Code, target, visit_number, sample) %>%
  count(Code, sample) %>% 
  arrange(Code) %>%
  rename(n.cc = n)
crayfish_visits <- data4jags %>%
  dplyr::filter(target == "Crayfish") %>%
  distinct(Code, target, visit_number, sample) %>%
  count(Code, sample) %>% 
  arrange(Code) %>%
  rename(n.rc = n)

visits = cbind(crayfish_visits[,3], carp_visits[,3])

occupancy <- matrix( c(1,1,
                       1,1,
                       1,1,
                       0,0,
                       1,1,
                       0,0,
                       1,1,
                       1,1,
                       1,1,
                       1,1,
                       1,1,
                       1,1,
                       0,0,
                       1,1,
                       1,1,
                       1,0,
                       1,1,
                       1,1), ncol = 2, byrow = T)
occupancy = occupancy[rep(seq_len(nrow(occupancy)), each = 10), ]

jd = jd.data[rep(seq_len(nrow(jd.data)), each = 10), ]
jd2 = jd2.data[rep(seq_len(nrow(jd.data)), each = 10), ]

# covraiate for depth
depth.data <- data4jags %>% group_by(Code, visit_site) %>%
  mutate(site_depth_m = mean(depth_m)) %>%
  distinct(Code, visit_site, site_depth_m) %>%
  pivot_wider(names_from = "visit_site", values_from = site_depth_m) %>%
  remove_rownames %>% column_to_rownames(var = "Code")
# covariate for julian day

area.acres <- data4jags %>% group_by(Code) %>%
  dplyr::select(area_acres) %>%
  distinct(Code, area_acres) %>%
  pivot_wider(names_from = "Code", values_from = area_acres) 


species <- data4jags %>% mutate(species = ifelse(target == "Crayfish", 1, 2)) %>%
  dplyr::select(species)

lake <- data4jags %>% ungroup() %>% mutate(lake_number =
  case_when(
  Code == "BDG" ~ 1, 
  Code == "BEN" ~ 2,
  Code == "CLR" ~ 3,
  Code == "FLF" ~ 4,
  Code == "FST" ~ 5,
  Code == "ILR" ~ 6,
  Code == "KAB" ~ 7,
  Code == "LEH" ~ 8,
  Code == "MIL" ~ 9,
  Code == "OWA" ~ 10,
  Code == "OWS" ~ 11,
  Code == "PHN" ~ 12,
  Code == "PKE" ~ 13,
  Code == "PRO" ~ 14,
  Code == "SHG" ~ 15,
  Code == "TEN" ~ 16,
  Code == "VER" ~ 17,
  Code == "WHB" ~ 18)) %>% dplyr::select(lake_number)

z.site.rc <- ifelse(rowSums(y.rc[3:7], na.rm = T) > 0, 1, NA)

# run the model for each of the species
jags.data.rc <- list(y = y.rc[3:7], 
                       zsite = z.site.rc,
                       unique.sites = 180,
                       n.samples = crayfish_visits[,3],
                       occupancy = occupancy[,1],
                       jd = jd, jd2 = jd2)

sink("eDNA.site.txt")
cat("
model {
#priors
  p.spp ~ dnorm(0, 1.75)
  theta0 ~ dbeta(1,1)
  a.jd ~ dnorm(0, 1.75) 
  a.jd.2 ~ dnorm(0, 1.75) 
  
  for (i in 1:unique.sites){
    # Biological
    theta[i] ~ dbern(theta0)
    zsite[i] ~ dbern(theta[i]*occupancy[i])
      
    for (j in 1:n.samples[i,]){
    # Detection
      logit(p[i,j]) <- p.spp + a.jd * jd[i,j] + a.jd.2 * jd2[i,j]
      y[i, j] ~ dbern(zsite[i]*p[i,j])
    }
  }
} # end jags model
",fill = TRUE)  # back to R code
sink()

params <- c("theta0", "p.spp", "a.jd", "a.jd.2")

na <- 1000; ni <- 10000; nt <- 3; nb <- 1000; nc <- 3 # short for test run


# Call JAGS from R (~44 min at 60,000 ni)
eDNA1.out <- jags(jags.data.rc, inits = NULL, params, "eDNA.site.txt", 
                  n.adapt = na, n.chains = nc, n.thin = nt, 
                  n.iter = ni, n.burnin = nb, parallel = TRUE)

print(eDNA1.out, dig = 2)
mcmcOutput::diagPlot(eDNA1.out)

plogis(eDNA1.out$mean$p.spp)

```


# UBMS occupancy model
```{r ubms}
library(ubms)

site_covs <- pres.abs.df %>% 
  distinct(Code, visit_site, .keep_all = T) %>%
  dplyr::select("Lake", "Code", "visit_number", "visit_site", "area_acres", 
                "littoral_area_acres", "perimeter_miles", "max_depth_ft", "mean_depth_ft") %>%
  mutate(lake_site = str_c(Code, visit_number))

y_stack <- pres.abs.df %>%
  dplyr::select("Code", "visit_number", "sample", "numdetection") %>%
  group_by(Code, sample) %>%
  pivot_wider(names_from = "visit_number", values_from = "numdetection")



sample_covs_names <- c("julian_day", "Clarity_m", "Temp_C", "mixed_to_bottom", 
                       "depth_m", "strat_zm", "lake_site")
sample_covs <- list(); i = 1

for (var in sample_covs_names) {
  temp <- pres.abs.df %>%
    dplyr::select("Code", "visit_number", "sample", var) %>%
    group_by(Code, sample) %>%
    pivot_wider(names_from = "visit_number", values_from = var)
  sample_covs[[length(sample_covs) + 1]] = temp
  i = i + 1
}
names(sample_covs) <- sample_covs_names


umf_stack <- unmarkedFrameOccu(y = y_stack[,3:7], siteCovs = site_covs,
                               obsCovs = list(date = sample_covs[["julian_day"]][,3:7], 
                                              depth = sample_covs[["depth_m"]][,3:7],
                                              clarity = sample_covs[["Clarity_m"]][,3:7],
                                              lake_site = sample_covs[["lake_site"]][,3:7]))

fit_stack <- stan_occu(~ date + (1|Code) + (1|lake_site)
                       ~ (1|Code) + (1|lake_site), 
                       data = umf_stack, chains = 3, iter = 2500)

# diagnostics
fit_stack
plot(fit_stack)

#M-B chi square
(fit_stack_gof <- gof(fit_stack, quiet = TRUE))
plot(fit_stack_gof)

#trace-plot
traceplot(fit_stack)

plot_marginal(fit_stack, "det")

sum_tab <- summary(fit_stack, "det")
names(fit_stack)
det_date <- extract(fit_stack, "beta_det[date]")[[1]]
hist(det_date , freq=FALSE)
lines(density(det_date ), col='red', lwd=2)


y_stack$rowsums <- rowSums(y_stack[,c(3:7)], na.rm = TRUE)
y_stack <- y_stack %>% 
  ungroup() %>%
  mutate(rowsums = ifelse(rowsums >= 1, 1, 0))

sum(y_stack$rowsums)
```


```{r crosshabitat, warning = F}
habitat <- read.csv("./data/lake_info_Cross.csv")
eDNA_DOW <- physical$DOW

lakes <- habitat %>% filter(DOW %in% eDNA_DOW)

### random plots 
mn <- map_data("state", "Minnesota")
physical %>%
  rowwise() %>%
  mutate(numAIS = as.factor(sum(c_across(ZM:RC))),
         numAIS = fct_relevel(numAIS, "1", "2", "3")) %>%
  ggplot() +
  geom_polygon(data = mn, mapping = aes(x = long, y = lat, group = group),
               color = "black", fill = "gray") +
  geom_point(aes(x = Long, y = Lat, color = numAIS), size = 2) +
  coord_fixed(1.3) +
  labs(title = "Objective 1 Study Lakes", y = "Longitude", x = "Latitude", colour = "Number of AIS") +
  scale_color_manual(values = wes_palette(n=3, name = "GrandBudapest1")) +
  theme_classic() + 
  theme(plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5)) 

table <- physical %>% 
  mutate(mean_depth_ft = as.numeric(mean_depth_ft)) %>%
  rename(`Lake area (acres)` = area_acres,
         `Littoral area (acres)` = littoral_area_acres,
         `Max depth (ft)` = max_depth_ft,
         `Mean depth (ft)` = mean_depth_ft,
         `Lake perimeter (mi)` = perimeter_miles) %>%
  pivot_longer(cols = `Lake area (acres)`:`Mean depth (ft)`, 
               names_to = 'Measurement Type',
               values_to = "measurement") %>%
  group_by(`Measurement Type`) %>%
  summarise(Median = median(measurement, na.rm = TRUE),
            Mean = mean(measurement, na.rm = TRUE),
            SD = sd(measurement, na.rm = TRUE)) %>%
  gt() %>%
  tab_header("Physical lake characteristics") %>%
  fmt_number(
    columns = 2:4,
    decimals = 1) %>%
  tab_source_note("Data from MN DNR")
gtsave(table , "physical_characteristics.png")
table
```


