---
title: "EDA"
author: "Christopher Rounds"
date: "6/17/2022"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(readxl) 
library(lubridate)
library(gt)
library(randomForest)
options(scipen = 999)

read_excel_allsheets <- function(filename, tibble = FALSE) {
    sheets <- readxl::excel_sheets(filename)
    x <- lapply(sheets, function(X) readxl::read_excel(filename, sheet = X))
    if (!tibble) x <- lapply(x, as.data.frame)
    names(x) <- sheets
    x
}
```



```{r cars}
lakesitecovariates %>% 
  mutate(ZM = as.logical(ZM), 
         Clarity_m = as.numeric(Clarity_m)) %>%
  ggplot(aes(x = ZM, y = Clarity_m)) + 
  geom_boxplot()

lakesitecovariates %>% 
  ggplot(aes(x = pH, y = Clarity_m, color = Code)) +
  geom_point() 

lakesitecovariates %>% 
  ggplot(aes(x = log(area_acres), y = pH, color = Code)) +
  geom_point() 

lakesitecovariates %>% 
  ggplot(aes(x = mean_depth_ft, y = Clarity_m, color = Code)) +
  geom_point() 

lakesitecovariates %>% 
  ggplot(aes(x = Temp_C, y = Clarity_m, color = Code)) +
  geom_point() + geom_line()

lakesitecovariates %>% 
  ggplot(aes(x = visit_number, y = Temp_C)) +
  geom_violin()

lakesitecovariates %>% 
  ggplot(aes(y = strat_zm, x = Temp_C, color = stratified)) +
  geom_point()
```


```{r pressure, echo=FALSE}
profiles %>%
  rename("visit" = "Visit #") %>%
  mutate('visit' = as.factor(visit),
         Lake = as.factor(Lake)) %>%
  ggplot() +
  geom_line(aes(x = Temp_C, y = -1*Depth_m, color = Lake)) + 
  facet_wrap(~visit, scales='free') +
  ylab("Depth (m)") +
  xlab("Temperature (C)")
```

```{r}
lakesitecovariates %>%
  ggplot() +
  geom_boxplot(aes(x = visit_number, y = Clarity_m))


lakesitecovariates %>%
  ggplot() +
  geom_line(aes(x = Date, y = Clarity_m, color = Lake)) +
  scale_x_date(date_breaks="1 month", date_labels="%b")
```

```{r}
temp_carp <- all_data_pcr %>% 
  dplyr::filter(CC == 1) %>%
  dplyr::filter(!grepl('00|111|211|311|411|511|5011|12', uid))

filter_carp <- temp_carp %>% group_by(Lake, visit_number) %>%
  summarise(mean_pos = mean(pres_abs), n())

```

